### ISSUE TITLE
配置了本地ollama以后，使用本地模型答题就不会修改操作了，大佬可以帮忙操作修改一下不！能加上您的企鹅最好了，我的企鹅：837289747

### ISSUE THREAD

**Issue by tonlyejun** [myxuebi/wjx-exam#1]
![screenshot-1735120568361](https://github.com/user-attachments/assets/da9cbaab-0419-4c2b-8ee5-782413a24272)

**Comment by myxuebi** [comment]
使用的什么模型？你的配置截个图

**Comment by tonlyejun** [comment]
大佬您好！给您添麻烦了！
在webui打开的地址是Open WebUI
以下是这个本地模型的一些信息





&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "myxuebi/wjx-exam"                                                                                    ***@***.***&gt;;
Date:&nbsp;Thu, Dec 26, 2024 08:09 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [myxuebi/wjx-exam] 配置了本地ollama以后，使用本地模型答题就不会修改操作了，大佬可以帮忙操作修改一下不！能加上您的企鹅最好了，我的企鹅：837289747 (Issue #1)





 
使用的什么模型？你的配置截个图

**Comment by tonlyejun** [comment]
> 使用的什么模型？你的配置截个图

大佬您好！给您添麻烦了！
在webui打开的地址是[Open WebUI](http://localhost:3000/)
以下是这个本地模型的一些信息
![ollama本地大模型](https://github.com/user-attachments/assets/40e13a27-4083-41f6-bce8-6285716c717d)
![ollama模型](https://github.com/user-attachments/assets/d94dfd92-d9aa-4230-8f4e-1c5c9dd68614)

**Comment by myxuebi** [comment]
![QQ20241227-185644](https://github.com/user-attachments/assets/04a8c7fa-f433-41b7-a914-aec31e42c8d3)
这个修改后的呢？

**Comment by myxuebi** [comment]
> > 使用的什么模型？你的配置截个图
> 
> 大佬您好！给您添麻烦了！ 在webui打开的地址是[Open WebUI](http://localhost:3000/) 以下是这个本地模型的一些信息 ![ollama本地大模型](https://private-user-images.githubusercontent.com/153411197/398919816-40e13a27-4083-41f6-bce8-6285716c717d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyOTcyNzksIm5iZiI6MTczNTI5Njk3OSwicGF0aCI6Ii8xNTM0MTExOTcvMzk4OTE5ODE2LTQwZTEzYTI3LTQwODMtNDFmNi1iY2U4LTYyODU3MTZjNzE3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QxMDU2MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWVhMDRmNzFmNzFiYWQwN2UwZmMxNWEwNzAwZDg3Nzk3MTkxZjY0YjhjYjcxZjg4ZjZiMzBmZGE3ZTkyY2JlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iwGy4sf0opD6m0BhHr3KEIVWgjGD4n4o8BMxYQJcy2o) ![ollama模型](https://private-user-images.githubusercontent.com/153411197/398919822-d94dfd92-d9aa-4230-8f4e-1c5c9dd68614.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyOTcyNzksIm5iZiI6MTczNTI5Njk3OSwicGF0aCI6Ii8xNTM0MTExOTcvMzk4OTE5ODIyLWQ5NGRmZDkyLWQ5YWEtNDIzMC04ZjRlLTFjNWM5ZGQ2ODYxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QxMDU2MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzEwNTQ3NWE4NWE0ZTRmYjZjMGRiMDhkMGExZTM5MzA0MjhhOTdjMTNjOWJkNmMyODAyYTRlNWExOWRjMjJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.q5HkesmgvQwhe_YaZisFiDrhqYRBTb-760DqKWLzc_Q)

![QQ20241227-185644](https://github.com/user-attachments/assets/edd979fd-ea12-4575-a9dd-60b5429deb26)
这个修改后的呢

**Comment by tonlyejun** [comment]
只修改url和model那里，其他的不知道怎么修改
![screenshot-1735297859818](https://github.com/user-attachments/assets/927a83e9-c55d-4d4c-a12b-a7d737d9e8f0)

**Comment by myxuebi** [comment]
> 只修改url和model那里，其他的不知道怎么修改 ![screenshot-1735297859818](https://private-user-images.githubusercontent.com/153411197/398924390-927a83e9-c55d-4d4c-a12b-a7d737d9e8f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyOTgyNDUsIm5iZiI6MTczNTI5Nzk0NSwicGF0aCI6Ii8xNTM0MTExOTcvMzk4OTI0MzkwLTkyN2E4M2U5LWM1NWQtNGQ0Yy1hMTJiLWE3ZDczN2Q5ZThmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QxMTEyMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDVkMjFhOWMyNjJjM2JhMDI3MDQyNTUzZGRjYmQ2NmRiN2MzMGQ3NThlMTcyZjcwYTZlNzFlMjE1MDE4YWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xX-KTC5CFGPc9bCAE-sqp2Q-UbZtrgK46hcwFOK24cc)

你修改url干什么？？本地运行不需要修改url

**Comment by tonlyejun** [comment]
那只需要改model那里就可以了是吧

**Comment by myxuebi** [comment]
> 那只需要改model那里就可以了是吧

在代码原有基础上 修改model类型就可以，如果是远程服务器，把localhost改成对应ip就好，url路径不能动，不然清求不到数据

**Comment by tonlyejun** [comment]
大佬，这个我们这边问卷星的活动链接是这样的：https://kaoshi.wjx.top/vm/YzBMwzP.aspx# ，他每个题目就是一页，不是向下面滑动的，这种类型的问卷星应该怎么修改代码，我用下载的源码运行，就会提示不支持的题目类型，然后直接运行结束了。我给您截了一张图。他这个比赛就是前面需要点击开始，然后每做一个题目就要点下一题。
![截图](https://github.com/user-attachments/assets/46c7e8ad-ffd0-461d-9f67-0fdea1aac9d2)

**Comment by tonlyejun** [comment]
我自己改了一下代码可以进入答题页面了，但是进入答题页面后发现他这个问卷里面的选项没有ABCD，程序还是没法运行。可以麻烦大佬帮忙修改一下。万分感谢
![截图](https://github.com/user-attachments/assets/ee177823-2651-47e8-a5a0-b7dd3614e2e8)

**Comment by myxuebi** [comment]
题目判断有问题 现已修复 从GitHub重新下载代码运行即可
![image](https://github.com/user-attachments/assets/25a2af36-ac6f-4e02-adea-b2d5afc11964)

**Comment by tonlyejun** [comment]
感谢大佬

**Comment by tonlyejun** [comment]
大佬，我下载了最新的源码，运行后依然不能做答。提示程序结束了。无论是用本地ollama还是通义千问api都是这样。
![截图](https://github.com/user-attachments/assets/f453db9a-0b0b-47c5-b23a-28a25e83b6e3)

**Comment by myxuebi** [comment]
好奇怪的环境 方便远程吗

**Comment by tonlyejun** [comment]
可以的，安装哪个远程软件呢？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月31日(周二) 晚上10:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [myxuebi/wjx-exam] 配置了本地ollama以后，使用本地模型答题就不会修改操作了，大佬可以帮忙操作修改一下不！能加上您的企鹅最好了，我的企鹅：837289747 (Issue #1)




 
好奇怪的环境 方便远程吗

**Comment by myxuebi** [comment]
> 可以的，安装哪个远程软件呢？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年12月31日(周二) 晚上10:28 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [myxuebi/wjx-exam] 配置了本地ollama以后，使用本地模型答题就不会修改操作了，大佬可以帮忙操作修改一下不！能加上您的企鹅最好了，我的企鹅：837289747 (Issue #1) 好奇怪的环境 方便远程吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

qq联系你了 同意下

**Comment by tonlyejun** [comment]
您方便的时候，辛苦您帮我看一下这个程序。您告诉我安装哪个远程软件就行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月31日(周二) 晚上10:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [myxuebi/wjx-exam] 配置了本地ollama以后，使用本地模型答题就不会修改操作了，大佬可以帮忙操作修改一下不！能加上您的企鹅最好了，我的企鹅：837289747 (Issue #1)




 
好奇怪的环境 方便远程吗
